DATASET:
  DATA_ROOT: ""
  TRAIN:
    IMG_PREFIX: ""
    ANN_FILE: ""
  VAL:
    IMG_PREFIX: ""
    ANN_FILE: ""
  VIDEO_ROOT: "/home/fjqmfl5676/PycharmProjects/Sign2Speech_inf/video/SEN0227.mp4"

  WORKER_PER_GPU: 16  #16

  TRANSFORM:
    RESIZE_IMG: (256, 256)
    TEMPORAL_SCALING: 1.0
    CROP_SIZE: (224, 224)
    TEMPORAL_CROP_RATIO: 0.0
    MEAN: (0.0637, 0.0988, 0.2312)
    STD: (0.0643, 0.0556, 0.1150)
  VOCABULARY:
    EXCLUDE_TOKENS:
#    - __ON__  #not used in ksl
    - __OFF__

SOLVER:
  BATCH_PER_GPU: 1 #2
  BIAS_LR_FACTOR: 1.0

  RAMPDOWN_ITERS: 0
  BASE_LR: 1e-4
  OPTIM_NAME: "Adam"
  SGD:
    MOMENTUM: 0.9
    WEIGHT_DECAY: 0.0005
    NESTEROV: true
  ADAM:
    BETA1: 0.9
    BETA2: 0.999
    EPS: 1.0e-08
    WEIGHT_DECAY: 1e-4

  LR_SCHEDULER_NAME: "WarmupMultiStepLR"
  STEPS: (40, 60,)
  GAMMA: 0.5
  RAMPDOWN_ITERS: 0
  WARMUP_FACTOR: 0
  WARMUP_ITERS: 0
  WARMUP_METHOD: "linear"
PERIODS:
  EVAL: 1
  CHECKPOINT: 1
  LOG_ITERS: 1
OUTPUT_DIR: outputs/inference
RESUME: "/home/fjqmfl5676/PycharmProjects/Sign2Speech_inf/model_params/pt_model_best.pth.tar"
GPU_ID: 5
NOTE: ""

SEED: 33
CUDNN_BENCHMARK: False
CUDNN_DETERMINISTIC: True

